default:
  grouping_vars:  # Variables that are used to group the data
    - simID
    - source
    - time
  weight:
    - count
  weighted_vars:
    - bmi
    - carbohydrate
    - death
    - disabilityweight
    - energyintake
    - height
    - income
    - fat
    - migrations
    - obesity
    - overweight
    - physicalactivity
    - protein
    - sector
    - sodium
    - weight
  prevalence:
    - asthma
    - ckd
    - diabetes
    - ihd
    - stroke
  stroke:
    - intracerebralhemorrhage
    - ischemicstroke
    - subarachnoidhemorrhage
  total:
    - daly
    - yld
    - yll

